# Generated by Django 4.2.7 on 2025-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=21, max_length=13),
            preserve_default=False,
        ),
    ]
