# Generated by Django 4.2.7 on 2025-04-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
