# Generated by Django 4.2.7 on 2025-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_user_address_user_dob_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.FileField(default='NULL', upload_to='uploads/'),
        ),
    ]
