# Generated by Django 4.2.7 on 2025-04-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(default='default.png', upload_to='media/'),
        ),
    ]
