# Generated by Django 4.2.7 on 2025-04-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('visibility', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_size', models.CharField(max_length=100)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.IntegerField()),
                ('is_favorite', models.IntegerField()),
                ('download_count', models.IntegerField(default=0)),
                ('view_counter', models.IntegerField(default=0)),
            ],
        ),
    ]
