# Generated by Django 4.2.7 on 2025-04-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='view_counter',
            new_name='view_count',
        ),
    ]
