# Generated by Django 4.2.7 on 2025-04-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_view_counter_uploads_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='view_count',
            new_name='view_counter',
        ),
    ]
