# Generated by Django 4.2.7 on 2025-04-23 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0003_rename_view_count_uploads_view_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
