# Generated by Django 4.2.7 on 2025-04-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_uploads_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='favorites',
        ),
    ]
