# Generated by Django 4.2.7 on 2025-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='is_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
