# Generated by Django 4.2.7 on 2025-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_favorite_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='notes_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
