# Generated by Django 4.2.7 on 2025-04-24 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0008_favorite_notes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='uploads',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
